language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - george-edison55-precise-backports
          packages:
            - clang-5.0
            - cmake-data
            - cmake
            - libuv
            - libc++
            - libc++abi
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"


before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake -j
  - make test
